- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy default
  template:
     src: default.j2
     dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: true
    
    
# nginx exporter


- name: install nginx exporter
  apt:
    name: prometheus-nginx-exporter
    state: present

- name: enable nginx exporter on boot up
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
