
- name: Install haproxy
  apt:
    name:
      - haproxy

- name: /etc/haproxy/haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart Haproxy

- name: Haproxy started
  service:
    name: haproxy
    enabled: yes
    state: started
  
- name: prometheus-haproxy-exporter 
  apt:
    name:
      - prometheus-haproxy-exporter 

- name: /etc/default/prometheus-haproxy-exporter
  template:
    dest: /etc/default/prometheus-haproxy-exporter
    src: prometheus-haproxy-exporter.j2
  notify: 
    - Restart Haproxy
    - Restart Prometheus-haproxy-exporter

- name: Haproxy exporter started
  service:
    name: prometheus-haproxy-exporter
    enabled: yes
    state: started
  
- name: Add Haproxy CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_haproxy_records | dict2items }}"
  delegate_to: "{{ groups['dns_primary'][0] }}"
  
