---

- name: Get InfluxDB file
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
    dest: /opt/influxdb_1.8.10_amd64.deb
    
    
- name: Install InfluxDB
  apt:
    deb: /opt/influxdb_1.8.10_amd64.deb
    state: present

- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart Influxdb

-  name: Start Influx service
   service:
     name: influxdb
     state: started

- name: Download Telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb
    dest: /opt/telegraf_1.28.2-1_amd64.deb

- name: Install Telegraf
  apt:
    deb: /opt/telegraf_1.28.2-1_amd64.deb
    state: present

- name: Reconfigure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
