---

- name: Get InfluxDB file
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
    dest: /opt/influxdb_1.8.10_amd64.deb
    checksum: sha256:b2ace09231575df7309a41cea6f9dc7ad716fe4389dc06ac04470a14bd411456
    
- name: Install InfluxDB
  apt:
    deb: /opt/influxdb_1.8.10_amd64.deb
    state: present

- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart Influxdb

-  name: Start Influx service
   service:
     name: influxdb
     state: started

- name: Download Telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb
    dest: /opt/telegraf_1.28.2-1_amd64.deb

- name: Install Telegraf
  apt:
    deb: /opt/telegraf_1.28.2-1_amd64.deb
    state: present

- name: Reconfigure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
  
- name: Make sure Telegraf is running
  service:
    name: telegraf
    state: started
    
- name: Install InfluxDB stat exporter from git
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/
    mode: '0500'
    owner: prometheus

- name: Import Influxdb Stat Expo Template
  template:
    src: exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    mode: '0644'
  notify: Restart systemd

- name: Start explorer on boot up
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: true
    
#Backup

- name: Make Backup owner of influxdb
  file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    mode: '0744'

- name: Cron job to backup Influx
  cron:
    name: influxd backup
    job: "rm -rf /home/backup/influxdb/*; influxd backup -portable /home/backup/influxdb"
    user: backup
    cron_file: influxdb-backup
    weekday: "1-5"
    hour: "12"
    minute: "0"

- name: Cron job to full backup server
  cron:
    name: influxd full backup
    job: " duplicity --no-encryption full /home/backup/influxdb/ rsync://{{user}}@backup.{{fqdn}}/influxdb"
    user: backup
    cron_file: influxdb-backup
    weekday: "1-5"
    hour: "12"
    minute: "0"

- name: Cron job to incremental backup server
  cron:
    name: influxd incremental backup
    job: " duplicity --no-encryption incremental /home/backup/influxdb/ rsync://{{user}}@backup.{{fqdn}}/influxdb"
    user: backup
    cron_file: influxdb-backup
    weekday: "1-5"
    hour: "12"
    minute: "0"    

