---
- name: Install InfluxDB and InfluxDB client
  apt:
    name: 
      - influxdb
      - influxdb-client
    state: latest
    
- name: Start InfluxDB
  service:
    name: influxdb
    state: started
    
- name: Influx Config
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart Influxdb

- name: Download Telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb
    dest: /opt/telegraf_1.28.2-1_amd64.deb

- name: Install Telegraf
  apt:
    deb: /opt/telegraf_1.28.2-1_amd64.deb

- name: Reconfigure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
