---
- name: Install required tools for Grafana installation
  apt:
    name:
      - apt-transport-https
    state: latest

# This module requires gpg
- name: Add an apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key

# This module requires python-distutils-extra, python-apt (python 2), and python3-distutils-extra, python3-apt (python 3)
- name: Add Grafana repository
  apt_repository:
    filename: grafana
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Dependencies for Grafana
  apt:
    name:
      - adduser
      - libfontconfig1

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
    dest: /opt/grafana_7.2.1_amd64.deb

- name: Install Grafana
  apt:
    deb: /opt/grafana_7.2.1_amd64.deb

- name: Reconfigure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Grafana Dashboard Setting
  template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/default.yaml
  notify: Restart Grafana

- name: Grafana Datasource Setting
  template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/default.yaml
  notify: Restart Grafana

- name: Main Dashboard Json
  copy:
    src: "../files/{{ item }}"
    dest: /etc/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - syslog.json
    - mysql.json
  notify: Restart Grafana


- name: Start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
