---
- name: Init
  hosts: init
  roles:
    - init
  tags:
    - init

- name: DNS server
  hosts: dns_servers
  roles:
    - bind
  tags:
    - bind

- name: DNS setup
  hosts: all
  roles:
    - dns_setup
  tags:
    - dns

- name: Docker setup
  hosts: all
  roles:
    - docker
  tags: 
    - doc

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - db

- name: Web server
  hosts: web_servers
  roles:
    - nginx
  tags:
    - web
    - nginx
    
- name: Agama
  hosts: agama
  roles:
    - agama
  tags:
    - agama

- name: Configure Prometheus
  hosts: prometheus
  roles:
    - prometheus
  tags:
    - promo

- name: Grafana
  hosts: grafana
  roles:
    - grafana
  tags:
    - grafana

- name: Influxdb
  hosts: influxdb
  roles:
    - influxdb
  tags:
    - influxdb
    
- name: Pinger
  hosts: pinger
  roles:
    - pinger  
  tags:
    - pinger

- name: Keepalived and Haproxy
  hosts: haproxy
  roles:
    - keepalived
    - haproxy
  tags:
    - ha  
    - keepalived
