---
- name: Init
  hosts: init
  roles:
    - init
    
- name: DNS server
  hosts: dns_servers
  roles:
    - bind

- name: DNS setup
  hosts: all
  roles:
    - dns_setup
  tags:
    - dns
    
- name: Docker setup
  hosts: all
  roles:
    - docker
  tags: 
    - doc
#added resolv.conf to uwsgi templates to from lab 5

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
#    - agama
#    - uwsgi
    - nginx
    
- name: Agama
  hosts: agama
  roles:
    - agama


- name: Configure Prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx
    
- name: Grafana
  hosts: grafana
  roles:
    - grafana
    
- name: Influxdb
  hosts: influxdb
  roles:
    - influxdb

    
- name: Pinger
  hosts: pinger
  roles:
    - pinger  

- name: Keepalived and Haproxy
  hosts: haproxy
  roles:
    - keepalived
    - haproxy
  tags:
    - ha  
