---
- name: Init
  hosts: all
  roles:
    - init
    
- name: DNS server
  hosts: dns_servers
  roles:
    - bind
    
#added resolv.conf to uwsgi templates to from lab 5

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
    
- name: Node Exporter
  hosts: node_exporters
  roles:
    - node_exporter

- name: Configure Prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx

