{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Influxdb Write rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  },
  {
   "title": "CPU load on VMs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "InfluxDb health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "MySQL status rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " (node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Nginx HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " nginx_up \n \n " }
   ]
  },
  {
   "title": "MySQL status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Bind9 status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bind_up" }
   ]
  }
 ]
}