{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL slave sql running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running "
    }
   ]
  },
  {
   "title": "MySQL slave io running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "Time series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "MySQL server ids",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id_bits"
    }
   ]
  }
 ]
}