- name: update DNS on  VM
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf 

- name: Stop systemd-resolved service
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
    
