---
  - name: Install mysql-server
    ansible.builtin.apt:
      name: mysql-server

  - name: Install Pymsql
    ansible.builtin.apt:
      name: python3-pymysql

  - name: Copying and restarting mysql
    ansible.builtin.template:
      src: override.cnf
      dest: /etc/mysql/mysql.conf.d/override.cnf
      mode: 0644
    notify: Restart mysql

  - name: Start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
    
  - name: Create Database 
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock 
    no_log: True 

  - name: Create User
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      host: "%"
      password: "{{ mysql_password }}"
      priv: '{{ mysql_database }}.*:ALL'
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true
