---
  - name: Install mysql-server
    ansible.builtin.apt:
      name: mysql-server

  - name: Install Pymsql
    ansible.builtin.apt:
      name: python3-pymysql

  - name: Copying and restarting mysql
    ansible.builtin.template:
      src: override.cnf
      dest: /etc/mysql/mysql.conf.d/override.cnf
      mode: 0644
    notify: Restart mysql

  - name: Start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
    
  - name: Create Database 
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock 
    no_log: True 

  - name: Create User
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      host: "%"
      password: "{{ mysql_password }}"
      priv: '{{ mysql_database }}.*:ALL'
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

#Mysql Exporter

  - name: Install MySQL exporter and python3-pymysql
    ansible.builtin.apt:
      name: 
        - prometheus-mysqld-exporter
        - python3-pymysql

  - name: Create directory
    ansible.builtin.file:
      path: /var/lib/prometheus
      state: directory

  - name: Configure MySQL exporter
    ansible.builtin.template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
      owner: prometheus
      group: prometheus
      mode: 0644
    notify: Restart MySQL exporter
    
  - name: Create MySQL exporter user
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_pass }}"
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: Force all notified handlers
    ansible.builtin.meta: flush_handlers
  
  - name: Start mysql exporter
    ansible.builtin.service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes

