---
  - name: Install mysql-server
    apt:
      name: mysql-server

  - name: Install Pymsql
    apt:
      name: python3-pymysql

  - name: Copying and restarting mysql
    template:
      src: override.cnf
      dest: /etc/mysql/mysql.conf.d/override.cnf
      mode: 0644
    notify: Restart mysql

  - name: Start mysql
    service:
      name: mysql
      state: started
      enabled: yes
    
  - name: Create Database 
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock 
    no_log: True 

  - name: Create User
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      host: "%"
      password: "{{ mysql_password }}"
      priv: '{{ mysql_database }}.*:ALL'
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

#Mysql Exporter

  - name: Install MySQL exporter and python3-pymysql
    apt:
      name: 
        - prometheus-mysqld-exporter
        - python3-pymysql

  - name: Create directory
    file:
      path: /var/lib/prometheus
      state: directory

  - name: Configure MySQL exporter
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
      owner: prometheus
      group: prometheus
      mode: 0644
    notify: Restart MySQL exporter
    
  - name: Create MySQL exporter user
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_pass }}"
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: Force all notified handlers
    meta: flush_handlers
  
  - name: Start mysql exporter
    service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes

#MySQL Backup

  - name: Make Backup owner of MySQL DIR
    file:
      path: /home/backup/mysql
      state: directory
      owner: backup
      mode: '0755'
      
  - name: MySQL backup user
    community.mysql.mysql_user:
      name: "{{ backup_user }}"
      password: "{{ backup_password }}"
      priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      
  - name: Make Backup Template
    template:
      src: my2.cnf.j2
      dest: /home/backup/.my.cnf
      owner: backup
      mode: '0400'

  - name: Make cron backup
    template:
      src: back.conf
      dest: /etc/cron.d/mysql-backup
      mode: '0400'
      owner: root

# lab 11 

  - name: Template mysql exporter replication metrics
    template:
      dest: /etc/default/prometheus-mysqld-exporter
      src: my3.cnf.j2
      mode: '0600'
      owner: prometheus
      group: prometheus
    notify: Restart MySQL exporter
    
  - name: MySQL replication user
    community.mysql.mysql_user:
      name: "{{ replication_user }}"
      password: "{{ replication_password }}"
      priv: "*.*:REPLICATION SLAVE"
      login_unix_socket: /var/run/mysqld/mysqld.sock

