---
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

# nginx exporter
  - name: Reload systemd
    shell: "systemctl daemon-reload"

  - name: Restart Nginx exporter
    service:
      name: prometheus-nginx-exporter
      state: restarted
      enabled: yes
