---
  - name: Systemctl daemon-reload
    ansible.builtin.shell: "systemctl daemon-reload"

  - name: Restart Nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
