---

  - name: Install node exporter
    apt:
      name: 
        - prometheus-node-exporter
        - nginx

  - name: Start node exporter
    service:
      name: prometheus-node-exporter
      state: started
      enabled: yes
