---

  - name: Install Prometheus
    apt:
      name: 
        - prometheus

  - name: Configure Prometheus
    template: 
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: 
      - Restart Prometheus
    
    
  - name: Configure Prometheus' web path
    template:
      src: prometheus.service.j2
      dest: /etc/default/prometheus
    notify: 
      - Systemctl daemon-reload
      - Restart Prometheus 

  - name: start prometheus
    service:
      name: prometheus
      state: started
      enabled: yes
      
  - name: Add Prometheus CNAME records
    community.general.nsupdate:
      key_name: "nsupdate.key"
      key_algorithm: "hmac-sha256"
      key_secret: "{{ dns_nsupdate_key }}"
      server: "localhost"
      zone: "{{ fqdn }}"
      record: "{{ item.key }}"
      type: "CNAME"
      value: "{{ item.value }}"
    loop: "{{ dns_prometheus_records | dict2items }}"
    delegate_to: "{{ groups['dns_primary'][0] }}"
