- name: Install docker.io and python3-docker
  apt:
    name: 
      - docker.io
      - python3-docker
    state: present

- name: Start + Enable Docker
  service:
    name: docker
    state: started
    enabled: yes
