- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Restart MySQL exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_host: "{{mysql_host}}"
    primary_user: "{{replication_user}}"
    primary_password: "{{replication_password}}"
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
