---

  - name: Systemctl daemon-reload
    ansible.builtin.shell: "systemctl daemon-reload"

  - name: Restart Prometheus
    ansible.builtin.service:
      name: prometheus
      state: restarted
      enabled: yes

  - name: restart Nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
