- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
      - prometheus-bind-exporter
    state: latest   

- name: Configure options.j2
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind
  no_log: yes


- name: Configure local.j2
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local     
  notify: Restart bind


- name: Configure db.rev.j2
  template:
    src: db.faaziz.j2
    dest: /var/cache/bind/rev.db
    force: no
  when: inventory_hostname in groups ['dns_primary']

- name: Configure fetirix.io.j2
  template:
    src: db.fetirix.j2
    dest: /var/cache/bind/db.{{ fqdn }}
    force: no
  notify:
    - Restart bind
    - Reload rndc
  when: inventory_hostname in groups ['dns_primary']


- name: Bind9 exporter
  apt:
    name: 
      - prometheus-bind-exporter

- name: Start Bind9 exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
    
- name: execute handlers
  meta: flush_handlers

- name: Start service bind9, if not started
  service:
    name: bind9
    state: started
    enabled: yes

- name: Add A server records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "A"
    value: "{{ item.value }}"
  loop: "{{ dns_a_records | dict2items }}"
  when: inventory_hostname in groups['dns_primary']


- name: Add DNS CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_dns_records | dict2items }}"
  delegate_to: "{{ groups['dns_primary'][0] }}"


