- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
      - prometheus-bind-exporter
    state: latest   

- name: Start service bind9, if not started
  service:
    name: bind9
    state: started
    enabled: yes

- name: Configure options.j2
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind



- name: Configure local.j2
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local     
  notify: Restart bind



- name: Configure db.rev.j2
  template:
    src: db.faaziz.j2
    dest: /var/cache/bind/rev.db
    force: no
  when: inventory_hostname in groups ['dns_primary']

- name: Configure fetirix.io.j2
  template:
    src: db.fetirix.j2
    dest: /var/cache/bind/db.{{ fqdn }}
    force: no
  notify:
    - Restart bind
    - Reload rndc
  when: inventory_hostname in groups ['dns_primary']

- name: Bind9 exporter
  apt:
    name: 
      - prometheus-bind-exporter

- name: Start Bind9 exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
    
- name: execute handlers
  meta: flush_handlers


- name: Create A records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key}}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ fqdn }}."
    record: "{{ item['subdomain'] }}.{{ fqdn }}."
    type: "A"
    value: "{{ item['ip'] }}"
  loop: "{{ a_records }}"
  when: inventory_hostname in groups ['dns_primary']

- name: Create CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  when: inventory_hostname in groups ['dns_primary']



