#- name: Ansible ping module
#  ansible.builtin.ping:
 - name: Update APT cache
   apt:
     cache_valid_time: 86400
     
 - name: Install node exporter
   apt:
     name: 
     - prometheus-node-exporter

 - name: Start node exporter
   service:
     name: prometheus-node-exporter
     state: started
     enabled: yes

 - name: Install up-to-date CA certificates
   apt:
     name: ca-certificates=20230311ubuntu0.20.04.1
     state: present

#Check if rsyslog is installed
 - name: Install Rsyslog
   apt:
     name: rsyslog
     state: latest

 - name: Reconfigure Rsyslog
   template:
     src: rsyslog.conf.j2
     dest: /etc/rsyslog.d/telegraf.conf
   notify: Restart Rsyslog
   
 - name: Start Rsyslog
   service:
     name: rsyslog
     state: started
#backup lab 9  
 - name: Add user backup 
   user:
     name: backup
     state: present
     home: /home/backup
     shell: /bin/bash
     generate_ssh_key: true 

 - name: Generate SSH keypair for user backup
   openssh_keypair:
     path: /home/backup/.ssh/id_rsa
     state: present
     owner: backup
     group: backup
     mode: '0644'
     
 - name : Template
   template:
     src: known_hosts.j2
     dest: /home/backup/.ssh/known_hosts
     owner: backup
     group: backup
     
#Backup lab 10

 - name: Make Backup owner for init
   file:
     path: /home/backup/restore
     state: directory
     owner: backup
     mode: '0744'

 - name: Duplicity
   apt:
     name: duplicity
     state: present

 #- name: add a new user juri
 #  ansible.builtin.user:
 #    name: juri

 #- name: add key for a user juri
 #  ansible.posix.authorized_key:
 #    user: juri  
 #    state: present
 #    key: https://github.com/hudolejev.keys

 #- name: add a new user roman
 #  ansible.builtin.user:
 #    name: roman

 #- name: add key for a user roman
 #  ansible.posix.authorized_key:
 #    user: roman  
 #    state: present
 #    key: https://github.com/romankuchin.keys


